#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

uv venv ~/venv/ -q --allow-existing
source ~/venv//bin/activate
#uv pip install ha-ffmpeg aiodhcpwatcher aiousbwatcher aiohasupervisor
uv pip install -r requirements.txt -r requirements_ha.txt